//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ApiRateLimit")]
pub struct Model {
    #[sea_orm(column_name = "IP", primary_key, auto_increment = false, unique)]
    pub ip: String,
    #[sea_orm(column_name = "Requests")]
    pub requests: i32,
    #[sea_orm(column_name = "WindowStart")]
    pub window_start: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
