//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Bans")]
pub struct Model {
    #[sea_orm(column_name = "IPAddress", primary_key, auto_increment = false)]
    pub ip_address: String,
    #[sea_orm(column_name = "BanTS")]
    pub ban_ts: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
