//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Licenses")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name", unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        super::package_licenses::Relation::Packages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::package_licenses::Relation::Licenses.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
