//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod accepted_terms;
pub mod account_types;
pub mod api_keys;
pub mod api_rate_limit;
pub mod bans;
pub mod dependency_types;
pub mod licenses;
pub mod official_providers;
pub mod package_bases;
pub mod package_blacklist;
pub mod package_comaintainers;
pub mod package_comments;
pub mod package_depends;
pub mod package_keywords;
pub mod package_licenses;
pub mod package_notifications;
pub mod package_relations;
pub mod package_requests;
pub mod package_sources;
pub mod package_votes;
pub mod packages;
pub mod relation_types;
pub mod request_types;
pub mod sessions;
pub mod ssh_pub_keys;
pub mod terms;
pub mod tu_vote_info;
pub mod tu_votes;
pub mod users;
