//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PackageDepends")]
pub struct Model {
    /// SeaORM requires all table to have a primary key, so add one here. See https://github.com/SeaQL/sea-orm/issues/485>.
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "PackageID")]
    pub package_id: u32,
    #[sea_orm(column_name = "DepTypeID")]
    pub dep_type_id: u8,
    #[sea_orm(column_name = "DepName")]
    pub dep_name: String,
    #[sea_orm(column_name = "DepDesc")]
    pub dep_desc: Option<String>,
    #[sea_orm(column_name = "DepCondition")]
    pub dep_condition: Option<String>,
    #[sea_orm(column_name = "DepArch")]
    pub dep_arch: Option<String>,
    #[sea_orm(column_name = "DepDist")]
    pub dep_dist: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::packages::Entity",
        from = "Column::PackageId",
        to = "super::packages::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Packages,
    #[sea_orm(
        belongs_to = "super::dependency_types::Entity",
        from = "Column::DepTypeId",
        to = "super::dependency_types::Column::Id",
        on_update = "Restrict",
        on_delete = "NoAction"
    )]
    DependencyTypes,
}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packages.def()
    }
}

impl Related<super::dependency_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DependencyTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
