//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PackageRequests")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u64,
    #[sea_orm(column_name = "ReqTypeID")]
    pub req_type_id: u8,
    #[sea_orm(column_name = "PackageBaseID")]
    pub package_base_id: Option<u32>,
    #[sea_orm(column_name = "PackageBaseName")]
    pub package_base_name: String,
    #[sea_orm(column_name = "MergeBaseName")]
    pub merge_base_name: Option<String>,
    #[sea_orm(column_name = "UsersID")]
    pub users_id: Option<u32>,
    #[sea_orm(column_name = "Comments", column_type = "Text")]
    pub comments: String,
    #[sea_orm(column_name = "ClosureComment", column_type = "Text")]
    pub closure_comment: String,
    #[sea_orm(column_name = "RequestTS")]
    pub request_ts: u64,
    #[sea_orm(column_name = "ClosedTS")]
    pub closed_ts: Option<u64>,
    #[sea_orm(column_name = "ClosedUID")]
    pub closed_uid: Option<u32>,
    #[sea_orm(column_name = "Status")]
    pub status: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::request_types::Entity",
        from = "Column::ReqTypeId",
        to = "super::request_types::Column::Id",
        on_update = "Restrict",
        on_delete = "NoAction"
    )]
    RequestTypes,
    #[sea_orm(
        belongs_to = "super::package_bases::Entity",
        from = "Column::PackageBaseId",
        to = "super::package_bases::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    PackageBases,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UsersId",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ClosedUid",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Users1,
}

impl Related<super::request_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RequestTypes.def()
    }
}

impl Related<super::package_bases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PackageBases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
