//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PackageKeywords")]
pub struct Model {
    #[sea_orm(column_name = "PackageBaseID", primary_key, auto_increment = false)]
    pub package_base_id: u32,
    #[sea_orm(column_name = "Keyword", primary_key, auto_increment = false)]
    pub keyword: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::package_bases::Entity",
        from = "Column::PackageBaseId",
        to = "super::package_bases::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    PackageBases,
}

impl Related<super::package_bases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PackageBases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
