//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Terms")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Description")]
    pub description: String,
    #[sea_orm(column_name = "URL")]
    pub url: String,
    #[sea_orm(column_name = "Revision")]
    pub revision: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accepted_terms::Entity")]
    AcceptedTerms,
}

impl Related<super::accepted_terms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcceptedTerms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
